export const endpoints = {
  flights: {
    searchFlightLocation: '/api/v1/flights/searchDestination',
    searchFlights: '/api/v1/flights/searchFlights',
    searchFlightsMultiStops: '/api/v1/flights/searchFlightsMultiStops',
    getFlightDetails: '/api/v1/flights/getFlightDetails',
    getMinPrice: '/api/v1/flights/getMinPrice',
    getMinPriceMultiStops: '/api/v1/flights/getMinPriceMultiStops',
    getSeatMap: '/api/v1/flights/getSeatMap',
  },
  hotels: {
    searchHotelDestination: '/api/v1/hotels/searchDestination',
    getFilter: '/api/v1/hotels/getFilter',
    getSortBy: '/api/v1/hotels/getSortBy',
    searchHotels: '/api/v1/hotels/searchHotels',
    searchHotelsByCoordinates: '/api/v1/hotels/searchHotelsByCoordinates',
    getHotelDetails: '/api/v1/hotels/getHotelDetails',
    getRoomAvailability: '/api/v1/hotels/getAvailability',
    getDescriptionAndInfo: '/api/v1/hotels/getDescriptionAndInfo',
    getRoomList: '/api/v1/hotels/getRoomList',
    paymentFeaturesOfTheHotel: '/api/v1/hotels/getPaymentFeatures',
    getHotelPolicies: '/api/v1/hotels/getHotelPolicies',
    propertyChildrenPolicies: '/api/v1/hotels/propertyChildrenPolicies',
    getHotelReviewsFilterMeta: '/api/v1/hotels/getHotelReviewsFilterMetadata',
    getHotelReviewScores: '/api/v1/hotels/getHotelReviewScores',
    getHotelReviewsTipsSort: '/api/v1/hotels/getHotelReviewsSortOption',
    getHotelReviewsTips: '/api/v1/hotels/getHotelReviews',
    getQuestionAndAnswer: '/api/v1/hotels/getQuestionAndAnswer',
    getNearbyCities: '/api/v1/hotels/getNearbyCities',
    getPopularAttractionNearBy: '/api/v1/hotels/getPopularAttractionNearBy',
    getRoomListWithAvailability: '/api/v1/hotels/getRoomListWithAvailability',
    getHotelPhotos: '/api/v1/hotels/getHotelPhotos',
    getHotelFacilities: '/api/v1/hotels/getHotelFacilities',
  },
  attractions: {
    searchAttractionLocation: '/api/v1/attraction/searchLocation',
    searchAttractions: '/api/v1/attraction/searchAttractions',
    getAvailabilityCalendar: '/api/v1/attraction/getAvailabilityCalendar',
    getAvailability: '/api/v1/attraction/getAvailability',
    getAttractionDetails: '/api/v1/attraction/getAttractionDetails',
    getAttractionReviews: '/api/v1/attraction/getAttractionReviews',
  },
  meta: {
    currency: '/api/v1/meta/getCurrency',
    language: '/api/v1/meta/getLanguage',
    location: '/api/v1/meta/getLocation',
  },
};
